// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQPk2grICcHJfW6QdAMwhKmU5lHh-CIy4',
    appId: '1:758634827875:web:1c42d7471af0f47775e856',
    messagingSenderId: '758634827875',
    projectId: 'doctorappointment-8956e',
    authDomain: 'doctorappointment-8956e.firebaseapp.com',
    storageBucket: 'doctorappointment-8956e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLC4uQNJYsf5dUh7H7ZFbMonja5kZu5U',
    appId: '1:758634827875:android:83627f56a170a88d75e856',
    messagingSenderId: '758634827875',
    projectId: 'doctorappointment-8956e',
    storageBucket: 'doctorappointment-8956e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMg1RMqTUpY4r0UK3k2_r2_BekaOzobU',
    appId: '1:758634827875:ios:c34c76acf914c4f575e856',
    messagingSenderId: '758634827875',
    projectId: 'doctorappointment-8956e',
    storageBucket: 'doctorappointment-8956e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMg1RMqTUpY4r0UK3k2_r2_BekaOzobU',
    appId: '1:758634827875:ios:c34c76acf914c4f575e856',
    messagingSenderId: '758634827875',
    projectId: 'doctorappointment-8956e',
    storageBucket: 'doctorappointment-8956e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQPk2grICcHJfW6QdAMwhKmU5lHh-CIy4',
    appId: '1:758634827875:web:7a462cc2f4633c9075e856',
    messagingSenderId: '758634827875',
    projectId: 'doctorappointment-8956e',
    authDomain: 'doctorappointment-8956e.firebaseapp.com',
    storageBucket: 'doctorappointment-8956e.firebasestorage.app',
  );
}
